# Generated by Django 4.0.3 on 2023-07-20 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hats_rest", "0003_alter_locationvo_closet_name"),
    ]

    operations = []
