# Generated by Django 4.0.3 on 2023-07-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0004_auto_20230720_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvo',
            name='closet_name',
            field=models.CharField(max_length=100),
        ),
    ]
